# Generated by Django 3.2.8 on 2021-10-22 07:12

from django.db import migrations, models
import productcurdrestapis.models


class Migration(migrations.Migration):

    dependencies = [
        ('productcurdrestapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=productcurdrestapis.models.nameFile),
        ),
    ]
